import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Custom manual sidebar with section headers
  tutorialSidebar: [
    {
      type: 'html',
      value: 'Get Started',
      className: 'sidebar-section-title',
    },
    'index', // docs/index.mdx
    'quickstart',
    'core-concepts',
    {
      type: 'category',
      label: 'Introduction',
      items: [{ type: 'autogenerated', dirName: '0_introduction' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [{ type: 'autogenerated', dirName: '1_getting-started' }],
    },
    {
      type: 'category',
      label: 'Build',
      items: [{ type: 'autogenerated', dirName: '2_build' }],
    },

    {
      type: 'html',
      value: 'References',
      className: 'sidebar-section-title',
    },
    {
      type: 'category',
      label: 'API References',
      items: [{ type: 'autogenerated', dirName: '3_api-references' }],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [{ type: 'autogenerated', dirName: '4_examples' }],
    },
    'faq',
  ],
};

export default sidebars;
