import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Custom manual sidebar with section headers
  tutorialSidebar: [
    // Get Started
    {
      type: 'html',
      value: 'Get Started',
      className: 'sidebar-section-title',
    },
    'index',
    'quickstart',
    'core-concepts',
    'introduction/what-can-you-build',
    'introduction/where-can-you-start',

    // Developer Console
    {
      type: 'html',
      value: 'Developer Console',
      className: 'sidebar-section-title',
    },
    'getting-started/create-your-account',
    'getting-started/register-a-license',
    'getting-started/authentication',

    // Tools
    {
      type: 'html',
      value: 'Tools',
      className: 'sidebar-section-title',
    },
    'build/building-with-tools/client-sdk-dimo-connect',
    'build/building-with-tools/server-sdk',
    'build/building-with-tools/agent-sdk',
    'build/building-with-tools/low-code-integrations',
    'build/building-with-ai/dimo-mcp-server',
    {
      type: 'doc',
      id: 'build/building-with-ai/developer-kit',
      label: 'Replit Developer Kit',
    },

    // API Reference
    {
      type: 'html',
      value: 'API Reference',
      className: 'sidebar-section-title',
    },
    'api-references/attestation-api',
    'api-references/conversations-api',
    'api-references/device-definitions-api',
    {
      type: 'category',
      label: 'Identity API',
      items: [
        { type: 'autogenerated', dirName: '3_api-references/3_identity-api' },
      ],
    },
    {
      type: 'category',
      label: 'Telemetry API',
      items: [
        { type: 'autogenerated', dirName: '3_api-references/4_telemetry-api' },
      ],
    },
    'api-references/token-exchange-api',
    'api-references/valuations-api',
    'api-references/vehicle-triggers-api',

    // Examples
    {
      type: 'html',
      value: 'Examples',
      className: 'sidebar-section-title',
    },
    'examples/build-examples',

    // FAQ
    {
      type: 'html',
      value: 'FAQ',
      className: 'sidebar-section-title',
    },
    'faq',
  ],
};

export default sidebars;
